# Generated by Django 3.2 on 2023-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movilidad_ruta_direccion', models.CharField(max_length=250)),
                ('movilidad_ruta_hora_recojo', models.TimeField()),
                ('movilidad_ruta_hora_retorno', models.TimeField()),
                ('movilidad_id', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
            ],
        ),
    ]
